apiVersion: "villip.carmier.fr/v1"
kind: "VillipProxy"
metadata:
  name: villip-priority
  namespace: default
spec:
  ports:
    - 8080

  ruleset:
    - matchlabels:
        ruleset: villiptests
        basedon: priority
  target:
    namespace: default
    name: smocker
    port: 8080
    uri: /