apiVersion: villip.carmier.fr/v1
kind: VillipRules
metadata:
  labels:
    app.kubernetes.io/name: villip-operator
    app.kubernetes.io/managed-by: kustomize
  name: villiprules-sample
spec:
  # TODO(user): Add fields here
