apiVersion: villip.carmier.fr/v1
kind: VillipRules
metadata:
  labels:
    app.kubernetes.io/name: villip-operator
    app.kubernetes.io/managed-by: kustomize
    ruleset: villiptest
  name: villiprules-sample
spec:
  size: 1
  ruleset:
  - matchlabels:
      ruleset: villiptest
  ports:
    - 8080